clc
clearall
formatshort
A=[1110;2101]%writeinstandardform
C=[3400]
b=[450;600]
n=size(A,2)%columninAmatrixorno.ofvariables
m=size(A,1)%rowsinAmatrixorconstraints
if(n>m)
nCm=nchoosek(n,m)%nchoosekcommandfornchoosek(orbinomialcoeff)
pair=nchoosek(1:n,m)%allpossiblecases(x1&x2;x1&x3;andsoon)
sol=[];
fori=1:nCm
y=zeros(n,1)%n-noofvariables,initializewithallvar(s)=0
x=A(:,pair(i,:))\b%pair(i,:)ithrow,includingallcolumns
ifall(x>=0&x~=inf&x~=-inf)
y(pair(i,:))=x
SmartBoy
sol=[sol,y]
end
end
else
error('nCmdoesnotexists')
end
Z=C*sol
[Zmax,Zindex]=max(Z)
bfs=sol(:,Zindex)
optimal_value=[bfs'Zmax]
optimal_bfs=array2table(optimal_value)
optimal_bfs.Properties.VariableNames(1:size(optimal_bfs,2))={'x_1','x_2','x_3','x_4','Z'